name: alchemy_cms

services:
  deps:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: bash -c "bundle check || bundle install && pnpm install"
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules

  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: bash -c "cd spec/dummy && rm -f tmp/pids/server.pid && bin/rails db:prepare && exec bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules
    depends_on:
      deps:
        condition: service_completed_successfully
      css:
        condition: service_started
      js:
        condition: service_started

  sass:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: pnpm run build:css --watch
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules
    depends_on:
      deps:
        condition: service_completed_successfully

  css:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: bash -c "cd spec/dummy && bin/rails dartsass:watch"
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules
    depends_on:
      deps:
        condition: service_completed_successfully

  js:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: pnpm run build:admin:dev
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - node_modules:/workspace/node_modules
    depends_on:
      deps:
        condition: service_completed_successfully

volumes:
  bundle:
  node_modules:
