# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 349f40f281622b46807143ab0e80daf8ca7ea2746bfe6dfd08bf12d882c0db6b722c5d69671cb6d5bc64d1c19a329d9251c1ac1758160a7027ee34020004d72c

test:
  secret_key_base: a1b53773d15fbcecbd23639acbdb0de069ca31d9fa1000aa789ee67ff4e3781d215309d1fa346f2c45fa34d96b9825109e4d8348e9968e5ccfe3c159212fc4f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
