# We use this file so that gettext can find them for translate the core alchemy modules
_('module: dashboard')
_('module: pages')
_('module: layoutpages')
_('module: users')
_('module: library')
_('module: attachments')
_('module: images')
_('module: languages')
_('logout')
_('home')
