name: Build

on:
  workflow_call:

jobs:
  check_yarn_lock:
    runs-on: ubuntu-latest
    name: Check yarn.lock
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-yarn-lock
        uses: tj-actions/changed-files@v41
        with:
          files: yarn.lock
    outputs:
      yarn_lock_changed: ${{ steps.changed-yarn-lock.outputs.any_changed }}
  build:
    runs-on: ubuntu-latest
    name: Build JS packages
    needs: check_yarn_lock
    if: ${{ needs.check_yarn_lock.outputs.yarn_lock_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - name: Restore node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules
      - name: Install dependencies
        run: yarn install
      - name: YARN build
        run: yarn build
