name: Lint

on: [pull_request]

concurrency:
  group: lint-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

permissions:
  contents: read

jobs:
  check_bot_commit:
    uses: ./.github/workflows/check-bot-commit.yml

  Standard:
    needs: [check_bot_commit]
    if: needs.check_bot_commit.outputs.is_bot != 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
          rubygems: "latest"
      - name: Lint Ruby files
        run: bundle exec standardrb
  ESLint:
    needs: [check_bot_commit]
    if: needs.check_bot_commit.outputs.is_bot != 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint code
        run: pnpm run eslint
  Prettier:
    needs: [check_bot_commit]
    if: needs.check_bot_commit.outputs.is_bot != 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint code
        run: pnpm run lint
  Herb:
    needs: [check_bot_commit]
    if: needs.check_bot_commit.outputs.is_bot != 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint erb files
        run: pnpm exec herb-lint

  lint-success:
    name: "Lint Success"
    if: always()
    needs: [check_bot_commit, Standard, ESLint, Prettier, Herb]
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        run: |
          for result in "${{ needs.Standard.result }}" "${{ needs.ESLint.result }}" "${{ needs.Prettier.result }}" "${{ needs.Herb.result }}"; do
            if [[ "$result" != "success" && "$result" != "skipped" ]]; then
              echo "Failed: $result"
              exit 1
            fi
          done
